ARG BASE=quay.io/centos/centos:stream8
ARG USER_NAME=percona
ARG USER_UID=1000

FROM "${BASE}"

ARG BASE
COPY scripts /opt/scripts
RUN /opt/scripts/ansible/init.sh "$(basename "${BASE}")"

USER "${USER_NAME}"
WORKDIR /app
ENTRYPOINT ["/opt/scripts/ansible/install.sh"]
CMD ["3.8"]
VOLUME ["/app"]
