- name: Current Alert Rule
  ansible.builtin.debug:
    msg: "{{ pmm_alert_item.name }}"

- name: Set Names and Labels
  ansible.builtin.set_fact:
    prefix_alert_name: "{{ pmm_templates_prefix }}{{ pmm_alert_item.name }}"
    prefix_template_name: "{{ pmm_templates_prefix }}{{ pmm_alert_item.template_name | default(pmm_alert_item.name) }}"
    labels: "{{ pmm_alert_item | json_query(\"custom_labels\") }}"

- name: Check Template
  ansible.builtin.debug:
    msg: "Template name '{{ prefix_template_name }}' does not exist."
  when: prefix_template_name not in pmm_updated_alert_templates

- block:
    - name: Clear Params and Set names
      ansible.builtin.set_fact:
        pmm_all_templates: ""

    - name: Get Params
      ansible.builtin.set_fact:
        pmm_all_templates: "{{ pmm_get_updated_templates.json['templates'] | selectattr('name','equalto', prefix_template_name ) | map(attribute='params')| flatten | default('') }}"
      ignore_errors: true
      no_log: true

    - name: Set params
      ansible.builtin.set_fact:
        pmm_param_name: "{{ pmm_all_templates[0]['name'] }}"
        pmm_param_float: "{{ pmm_alert_list | json_query(\"[?name==`\" + pmm_alert_item.name + \"`].threshold\") }}"
        pmm_param_type: "{{ pmm_all_templates[0]['type'] }}"
      when: pmm_all_templates | length > 0

    - name: Set Alert Filter
      ansible.builtin.set_fact:
        pmm_alerting_filters: "{{ pmm_alert_list | json_query(\"[?name==`\" + pmm_alert_item.name + \"`].filters\") }}"

    - name: Create alerts
      ansible.builtin.uri:
        url: '{{ pmm_server_uri }}{{ pmm_api_alerting_rules_create }}'
        method: POST
        user: '{{ pmm_api_credentials[0] }}'
        password: '{{ pmm_api_credentials[1] }}'
        body: |
              {
                "custom_labels": {% if labels is defined and labels | length > 0 %}
                {{ labels }}
                {% else %}
                {}
                {% endif %},
                "severity": "SEVERITY_{{ pmm_alerting_templates['templates'] | selectattr('name', 'equalto', prefix_template_name) | map(attribute='severity') | join | upper }}",
                "template_name": "{{ prefix_template_name }}",
                "name": "{{ prefix_alert_name }}",
                "filters": {{ pmm_alerting_filters | flatten }},
                "group": "default-alert-group",
                {% if pmm_all_templates is defined and pmm_all_templates | length > 0 %}
                "params": [
                  {
                    "name": "{{ pmm_param_name | default('') }}",
                    "type": "{{ pmm_param_type | default('') }}",
                    "float": {% if pmm_param_float is defined and pmm_param_float | length > 0 %} "{{ pmm_param_float[0] | default(0) }}"  {% else %} "{{ pmm_all_templates[0]['float']['default'] | default(0) }}" {% endif %}
                  }
                ],
                {% endif %}
                "folder_uid": '{{ pmm_alerting_folder_uid }}'
              }
        force_basic_auth: yes
        status_code:
          - 200
          - 409
        body_format: json
        validate_certs: '{{ pmm_server_insecure }}'
  when: (pmm_get_alert_rules == "" or (prefix_alert_name is defined and prefix_alert_name not in pmm_existing_alert_rules)) and prefix_template_name in pmm_updated_alert_templates
  
