---
- name: Run preflight checks
  ansible.builtin.import_playbook: assertions.yaml
  tags:
    - always

- name: Setup PMM client
  hosts: pmm_clients
  gather_facts: false
  pre_tasks:
    - block:
        - name: Check inventory
          ansible.builtin.include_role:
            name: pmm
            tasks_from: check-inventory.yaml
      delegate_to: localhost

  tags:
    - pmm-client

  roles:
    - role: pmm-client
...
