---
- name: Prepare the PostgreSQL container image
  ansible.builtin.include_role:
    name: container
  vars:
    container_image: '{{ tools_postgresql_image }}:{{ tools_postgresql_image_tag }}'

- name: Check for tools_postgresql_conf
  ansible.builtin.stat:
    path: '{{ tools_postgresql_conf }}'
  register: tools_stat_postgresql_conf

- name: Ensure that the mounted files exist
  ansible.builtin.copy:
    dest: '{{ tools_postgresql_conf }}'
    content: >
      # This file is unmanaged
    mode: u=rw,g=r,o=
  when: not tools_stat_postgresql_conf.stat.exists

- name: Add alias for PostgreSQL CLI
  ansible.builtin.lineinfile:
    path: '{{ tools_profile_path }}'
    create: yes
    line: "alias psql{{ tools_postgresql_image_tag }}='podman run --rm -it --entrypoint=psql -v {{ tools_postgresql_conf }}:/home/postgres/{{ tools_postgresql_conf | basename }}:z {{ tools_postgresql_image }}:{{ tools_postgresql_image_tag }}'"
    owner: '{{ ansible_env.USER }}'
    mode: u=rw,g=r,o=
...
