---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  tags:
    - sudo

- name: Install extra tools
  ansible.builtin.package:
    name: "{{ tools_packages }}"
    state: present
  become: yes
  tags:
    - sudo

- name: Install percona-release package dependencies
  ansible.builtin.package:
    name: "{{ tools_percona_release_dependencies }}"
    state: present
  become: yes
  tags:
    - sudo

- name: Install percona-release
  ansible.builtin.apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"
  become: yes
  tags:
    - sudo

- name: Setup percona toolkit repo
  ansible.builtin.command: "percona-release enable {{ tools_percona_toolkit_repo }}"
  become: yes
  tags:
    - sudo

- name: Install percona toolkit
  ansible.builtin.apt:
    name: percona-toolkit
    state: present
  become: yes
  tags:
    - sudo
...
