---
name: Go Tests
on:
  pull_request:
    branches:
    - main
    paths:
    - '**.go'
    - 'go.mod'
    - 'go.sum'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.23
          check-latest: true

      - name: Checkout codebase
        uses: actions/checkout@v4.2.2

      - name: Perform checks
        run: |
          install -d build
          touch build/ansible
          make pack
          make test
...
