---
name: Go Tests
on:
  pull_request:
    branches:
    - main
    paths:
    - '**.go'
    - 'go.mod'
    - 'go.sum'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Perform checks
        run: |
          install -d build
          touch build/ansible
          go fmt ./...
          git diff --exit-code --quiet
          go vet -unusedresult -bools -copylocks -framepointer -httpresponse -json -stdmethods -printf -stringintconv -unmarshal -unsafeptr ./...
          git diff --exit-code --quiet
          go test ./...
...
