---
name: Go Tests
on:
  pull_request:
    branches:
    - main
    paths:
    - '**.go'
    - 'go.mod'
    - 'go.sum'
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Prepare Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.23.6'
          check-latest: false

      - name: Checkout codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Perform checks
        run: |
          install -d build
          touch build/ansible
          make pack
          make test
...
